/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesVastuRouteImport } from './routes/services/vastu'
import { Route as ServicesPalmReadingRouteImport } from './routes/services/palm-reading'
import { Route as ServicesNumerologyRouteImport } from './routes/services/numerology'
import { Route as ServicesMarriageMatchingRouteImport } from './routes/services/marriage-matching'
import { Route as ServicesKundaliRouteImport } from './routes/services/kundali'
import { Route as ServicesGemstoneRouteImport } from './routes/services/gemstone'
import { Route as ServicesCareerGuidanceRouteImport } from './routes/services/career-guidance'
import { Route as ServicesAstrologyRouteImport } from './routes/services/astrology'
import { Route as ReportsWealthGrowthRouteImport } from './routes/reports/wealth-growth'
import { Route as ReportsMarriageRouteImport } from './routes/reports/marriage'
import { Route as ReportsHealthWellnessRouteImport } from './routes/reports/health-wellness'
import { Route as ReportsEducationRouteImport } from './routes/reports/education'
import { Route as ReportsCareerRouteImport } from './routes/reports/career'
import { Route as ReportsBirthEarlyLifeRouteImport } from './routes/reports/birth-early-life'
import { Route as HoroscopesMonthlyRouteImport } from './routes/horoscopes/monthly'
import { Route as HoroscopesDailyRouteImport } from './routes/horoscopes/daily'
import { Route as FreeToolsNumerologyRouteImport } from './routes/free-tools/numerology'
import { Route as FreeToolsKundliRouteImport } from './routes/free-tools/kundli'
import { Route as FreeToolsDailyHoroscopeRouteImport } from './routes/free-tools/daily-horoscope'
import { Route as FreeToolsCompatibilityRouteImport } from './routes/free-tools/compatibility'
import { Route as FreeToolsBasicKundaliRouteImport } from './routes/free-tools/basic-kundali'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVastuRoute = ServicesVastuRouteImport.update({
  id: '/services/vastu',
  path: '/services/vastu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPalmReadingRoute = ServicesPalmReadingRouteImport.update({
  id: '/services/palm-reading',
  path: '/services/palm-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNumerologyRoute = ServicesNumerologyRouteImport.update({
  id: '/services/numerology',
  path: '/services/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarriageMatchingRoute =
  ServicesMarriageMatchingRouteImport.update({
    id: '/services/marriage-matching',
    path: '/services/marriage-matching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesKundaliRoute = ServicesKundaliRouteImport.update({
  id: '/services/kundali',
  path: '/services/kundali',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGemstoneRoute = ServicesGemstoneRouteImport.update({
  id: '/services/gemstone',
  path: '/services/gemstone',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCareerGuidanceRoute = ServicesCareerGuidanceRouteImport.update({
  id: '/services/career-guidance',
  path: '/services/career-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAstrologyRoute = ServicesAstrologyRouteImport.update({
  id: '/services/astrology',
  path: '/services/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsWealthGrowthRoute = ReportsWealthGrowthRouteImport.update({
  id: '/reports/wealth-growth',
  path: '/reports/wealth-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMarriageRoute = ReportsMarriageRouteImport.update({
  id: '/reports/marriage',
  path: '/reports/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHealthWellnessRoute = ReportsHealthWellnessRouteImport.update({
  id: '/reports/health-wellness',
  path: '/reports/health-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEducationRoute = ReportsEducationRouteImport.update({
  id: '/reports/education',
  path: '/reports/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCareerRoute = ReportsCareerRouteImport.update({
  id: '/reports/career',
  path: '/reports/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBirthEarlyLifeRoute = ReportsBirthEarlyLifeRouteImport.update({
  id: '/reports/birth-early-life',
  path: '/reports/birth-early-life',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopesMonthlyRoute = HoroscopesMonthlyRouteImport.update({
  id: '/horoscopes/monthly',
  path: '/horoscopes/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopesDailyRoute = HoroscopesDailyRouteImport.update({
  id: '/horoscopes/daily',
  path: '/horoscopes/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolsNumerologyRoute = FreeToolsNumerologyRouteImport.update({
  id: '/free-tools/numerology',
  path: '/free-tools/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolsKundliRoute = FreeToolsKundliRouteImport.update({
  id: '/free-tools/kundli',
  path: '/free-tools/kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolsDailyHoroscopeRoute = FreeToolsDailyHoroscopeRouteImport.update({
  id: '/free-tools/daily-horoscope',
  path: '/free-tools/daily-horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolsCompatibilityRoute = FreeToolsCompatibilityRouteImport.update({
  id: '/free-tools/compatibility',
  path: '/free-tools/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolsBasicKundaliRoute = FreeToolsBasicKundaliRouteImport.update({
  id: '/free-tools/basic-kundali',
  path: '/free-tools/basic-kundali',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/free-tools/basic-kundali': typeof FreeToolsBasicKundaliRoute
  '/free-tools/compatibility': typeof FreeToolsCompatibilityRoute
  '/free-tools/daily-horoscope': typeof FreeToolsDailyHoroscopeRoute
  '/free-tools/kundli': typeof FreeToolsKundliRoute
  '/free-tools/numerology': typeof FreeToolsNumerologyRoute
  '/horoscopes/daily': typeof HoroscopesDailyRoute
  '/horoscopes/monthly': typeof HoroscopesMonthlyRoute
  '/reports/birth-early-life': typeof ReportsBirthEarlyLifeRoute
  '/reports/career': typeof ReportsCareerRoute
  '/reports/education': typeof ReportsEducationRoute
  '/reports/health-wellness': typeof ReportsHealthWellnessRoute
  '/reports/marriage': typeof ReportsMarriageRoute
  '/reports/wealth-growth': typeof ReportsWealthGrowthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/career-guidance': typeof ServicesCareerGuidanceRoute
  '/services/gemstone': typeof ServicesGemstoneRoute
  '/services/kundali': typeof ServicesKundaliRoute
  '/services/marriage-matching': typeof ServicesMarriageMatchingRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/services/palm-reading': typeof ServicesPalmReadingRoute
  '/services/vastu': typeof ServicesVastuRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/free-tools/basic-kundali': typeof FreeToolsBasicKundaliRoute
  '/free-tools/compatibility': typeof FreeToolsCompatibilityRoute
  '/free-tools/daily-horoscope': typeof FreeToolsDailyHoroscopeRoute
  '/free-tools/kundli': typeof FreeToolsKundliRoute
  '/free-tools/numerology': typeof FreeToolsNumerologyRoute
  '/horoscopes/daily': typeof HoroscopesDailyRoute
  '/horoscopes/monthly': typeof HoroscopesMonthlyRoute
  '/reports/birth-early-life': typeof ReportsBirthEarlyLifeRoute
  '/reports/career': typeof ReportsCareerRoute
  '/reports/education': typeof ReportsEducationRoute
  '/reports/health-wellness': typeof ReportsHealthWellnessRoute
  '/reports/marriage': typeof ReportsMarriageRoute
  '/reports/wealth-growth': typeof ReportsWealthGrowthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/career-guidance': typeof ServicesCareerGuidanceRoute
  '/services/gemstone': typeof ServicesGemstoneRoute
  '/services/kundali': typeof ServicesKundaliRoute
  '/services/marriage-matching': typeof ServicesMarriageMatchingRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/services/palm-reading': typeof ServicesPalmReadingRoute
  '/services/vastu': typeof ServicesVastuRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/free-tools/basic-kundali': typeof FreeToolsBasicKundaliRoute
  '/free-tools/compatibility': typeof FreeToolsCompatibilityRoute
  '/free-tools/daily-horoscope': typeof FreeToolsDailyHoroscopeRoute
  '/free-tools/kundli': typeof FreeToolsKundliRoute
  '/free-tools/numerology': typeof FreeToolsNumerologyRoute
  '/horoscopes/daily': typeof HoroscopesDailyRoute
  '/horoscopes/monthly': typeof HoroscopesMonthlyRoute
  '/reports/birth-early-life': typeof ReportsBirthEarlyLifeRoute
  '/reports/career': typeof ReportsCareerRoute
  '/reports/education': typeof ReportsEducationRoute
  '/reports/health-wellness': typeof ReportsHealthWellnessRoute
  '/reports/marriage': typeof ReportsMarriageRoute
  '/reports/wealth-growth': typeof ReportsWealthGrowthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/career-guidance': typeof ServicesCareerGuidanceRoute
  '/services/gemstone': typeof ServicesGemstoneRoute
  '/services/kundali': typeof ServicesKundaliRoute
  '/services/marriage-matching': typeof ServicesMarriageMatchingRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/services/palm-reading': typeof ServicesPalmReadingRoute
  '/services/vastu': typeof ServicesVastuRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/my-bookings'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/article/$slug'
    | '/free-tools/basic-kundali'
    | '/free-tools/compatibility'
    | '/free-tools/daily-horoscope'
    | '/free-tools/kundli'
    | '/free-tools/numerology'
    | '/horoscopes/daily'
    | '/horoscopes/monthly'
    | '/reports/birth-early-life'
    | '/reports/career'
    | '/reports/education'
    | '/reports/health-wellness'
    | '/reports/marriage'
    | '/reports/wealth-growth'
    | '/services/astrology'
    | '/services/career-guidance'
    | '/services/gemstone'
    | '/services/kundali'
    | '/services/marriage-matching'
    | '/services/numerology'
    | '/services/palm-reading'
    | '/services/vastu'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/my-bookings'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/article/$slug'
    | '/free-tools/basic-kundali'
    | '/free-tools/compatibility'
    | '/free-tools/daily-horoscope'
    | '/free-tools/kundli'
    | '/free-tools/numerology'
    | '/horoscopes/daily'
    | '/horoscopes/monthly'
    | '/reports/birth-early-life'
    | '/reports/career'
    | '/reports/education'
    | '/reports/health-wellness'
    | '/reports/marriage'
    | '/reports/wealth-growth'
    | '/services/astrology'
    | '/services/career-guidance'
    | '/services/gemstone'
    | '/services/kundali'
    | '/services/marriage-matching'
    | '/services/numerology'
    | '/services/palm-reading'
    | '/services/vastu'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/my-bookings'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/article/$slug'
    | '/free-tools/basic-kundali'
    | '/free-tools/compatibility'
    | '/free-tools/daily-horoscope'
    | '/free-tools/kundli'
    | '/free-tools/numerology'
    | '/horoscopes/daily'
    | '/horoscopes/monthly'
    | '/reports/birth-early-life'
    | '/reports/career'
    | '/reports/education'
    | '/reports/health-wellness'
    | '/reports/marriage'
    | '/reports/wealth-growth'
    | '/services/astrology'
    | '/services/career-guidance'
    | '/services/gemstone'
    | '/services/kundali'
    | '/services/marriage-matching'
    | '/services/numerology'
    | '/services/palm-reading'
    | '/services/vastu'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  FreeToolsBasicKundaliRoute: typeof FreeToolsBasicKundaliRoute
  FreeToolsCompatibilityRoute: typeof FreeToolsCompatibilityRoute
  FreeToolsDailyHoroscopeRoute: typeof FreeToolsDailyHoroscopeRoute
  FreeToolsKundliRoute: typeof FreeToolsKundliRoute
  FreeToolsNumerologyRoute: typeof FreeToolsNumerologyRoute
  HoroscopesDailyRoute: typeof HoroscopesDailyRoute
  HoroscopesMonthlyRoute: typeof HoroscopesMonthlyRoute
  ReportsBirthEarlyLifeRoute: typeof ReportsBirthEarlyLifeRoute
  ReportsCareerRoute: typeof ReportsCareerRoute
  ReportsEducationRoute: typeof ReportsEducationRoute
  ReportsHealthWellnessRoute: typeof ReportsHealthWellnessRoute
  ReportsMarriageRoute: typeof ReportsMarriageRoute
  ReportsWealthGrowthRoute: typeof ReportsWealthGrowthRoute
  ServicesAstrologyRoute: typeof ServicesAstrologyRoute
  ServicesCareerGuidanceRoute: typeof ServicesCareerGuidanceRoute
  ServicesGemstoneRoute: typeof ServicesGemstoneRoute
  ServicesKundaliRoute: typeof ServicesKundaliRoute
  ServicesMarriageMatchingRoute: typeof ServicesMarriageMatchingRoute
  ServicesNumerologyRoute: typeof ServicesNumerologyRoute
  ServicesPalmReadingRoute: typeof ServicesPalmReadingRoute
  ServicesVastuRoute: typeof ServicesVastuRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vastu': {
      id: '/services/vastu'
      path: '/services/vastu'
      fullPath: '/services/vastu'
      preLoaderRoute: typeof ServicesVastuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/palm-reading': {
      id: '/services/palm-reading'
      path: '/services/palm-reading'
      fullPath: '/services/palm-reading'
      preLoaderRoute: typeof ServicesPalmReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/numerology': {
      id: '/services/numerology'
      path: '/services/numerology'
      fullPath: '/services/numerology'
      preLoaderRoute: typeof ServicesNumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marriage-matching': {
      id: '/services/marriage-matching'
      path: '/services/marriage-matching'
      fullPath: '/services/marriage-matching'
      preLoaderRoute: typeof ServicesMarriageMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kundali': {
      id: '/services/kundali'
      path: '/services/kundali'
      fullPath: '/services/kundali'
      preLoaderRoute: typeof ServicesKundaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gemstone': {
      id: '/services/gemstone'
      path: '/services/gemstone'
      fullPath: '/services/gemstone'
      preLoaderRoute: typeof ServicesGemstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/career-guidance': {
      id: '/services/career-guidance'
      path: '/services/career-guidance'
      fullPath: '/services/career-guidance'
      preLoaderRoute: typeof ServicesCareerGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/astrology': {
      id: '/services/astrology'
      path: '/services/astrology'
      fullPath: '/services/astrology'
      preLoaderRoute: typeof ServicesAstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/wealth-growth': {
      id: '/reports/wealth-growth'
      path: '/reports/wealth-growth'
      fullPath: '/reports/wealth-growth'
      preLoaderRoute: typeof ReportsWealthGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/marriage': {
      id: '/reports/marriage'
      path: '/reports/marriage'
      fullPath: '/reports/marriage'
      preLoaderRoute: typeof ReportsMarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/health-wellness': {
      id: '/reports/health-wellness'
      path: '/reports/health-wellness'
      fullPath: '/reports/health-wellness'
      preLoaderRoute: typeof ReportsHealthWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/education': {
      id: '/reports/education'
      path: '/reports/education'
      fullPath: '/reports/education'
      preLoaderRoute: typeof ReportsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/career': {
      id: '/reports/career'
      path: '/reports/career'
      fullPath: '/reports/career'
      preLoaderRoute: typeof ReportsCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/birth-early-life': {
      id: '/reports/birth-early-life'
      path: '/reports/birth-early-life'
      fullPath: '/reports/birth-early-life'
      preLoaderRoute: typeof ReportsBirthEarlyLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopes/monthly': {
      id: '/horoscopes/monthly'
      path: '/horoscopes/monthly'
      fullPath: '/horoscopes/monthly'
      preLoaderRoute: typeof HoroscopesMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopes/daily': {
      id: '/horoscopes/daily'
      path: '/horoscopes/daily'
      fullPath: '/horoscopes/daily'
      preLoaderRoute: typeof HoroscopesDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tools/numerology': {
      id: '/free-tools/numerology'
      path: '/free-tools/numerology'
      fullPath: '/free-tools/numerology'
      preLoaderRoute: typeof FreeToolsNumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tools/kundli': {
      id: '/free-tools/kundli'
      path: '/free-tools/kundli'
      fullPath: '/free-tools/kundli'
      preLoaderRoute: typeof FreeToolsKundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tools/daily-horoscope': {
      id: '/free-tools/daily-horoscope'
      path: '/free-tools/daily-horoscope'
      fullPath: '/free-tools/daily-horoscope'
      preLoaderRoute: typeof FreeToolsDailyHoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tools/compatibility': {
      id: '/free-tools/compatibility'
      path: '/free-tools/compatibility'
      fullPath: '/free-tools/compatibility'
      preLoaderRoute: typeof FreeToolsCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tools/basic-kundali': {
      id: '/free-tools/basic-kundali'
      path: '/free-tools/basic-kundali'
      fullPath: '/free-tools/basic-kundali'
      preLoaderRoute: typeof FreeToolsBasicKundaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestimonialsRoute: TestimonialsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  FreeToolsBasicKundaliRoute: FreeToolsBasicKundaliRoute,
  FreeToolsCompatibilityRoute: FreeToolsCompatibilityRoute,
  FreeToolsDailyHoroscopeRoute: FreeToolsDailyHoroscopeRoute,
  FreeToolsKundliRoute: FreeToolsKundliRoute,
  FreeToolsNumerologyRoute: FreeToolsNumerologyRoute,
  HoroscopesDailyRoute: HoroscopesDailyRoute,
  HoroscopesMonthlyRoute: HoroscopesMonthlyRoute,
  ReportsBirthEarlyLifeRoute: ReportsBirthEarlyLifeRoute,
  ReportsCareerRoute: ReportsCareerRoute,
  ReportsEducationRoute: ReportsEducationRoute,
  ReportsHealthWellnessRoute: ReportsHealthWellnessRoute,
  ReportsMarriageRoute: ReportsMarriageRoute,
  ReportsWealthGrowthRoute: ReportsWealthGrowthRoute,
  ServicesAstrologyRoute: ServicesAstrologyRoute,
  ServicesCareerGuidanceRoute: ServicesCareerGuidanceRoute,
  ServicesGemstoneRoute: ServicesGemstoneRoute,
  ServicesKundaliRoute: ServicesKundaliRoute,
  ServicesMarriageMatchingRoute: ServicesMarriageMatchingRoute,
  ServicesNumerologyRoute: ServicesNumerologyRoute,
  ServicesPalmReadingRoute: ServicesPalmReadingRoute,
  ServicesVastuRoute: ServicesVastuRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
